services:
    Erichard\GlideBundle\GlideUrlBuilder:
        public: false
        arguments:
            $signkey: "%erichard_glide.sign_key%"

    Erichard\GlideBundle\Twig\GlideExtension:
        public: false
        arguments:
            - "@Erichard\\GlideBundle\\GlideUrlBuilder"
        tags:
            - { name: twig.extension }

    erichard_glide.symfony_response_factory:
        class: Erichard\GlideBundle\SymfonyResponseFactory
        public: false

    erichard_glide.server:
        class: League\Glide\Server
        public: false
        abstract: true
        factory: [ League\Glide\ServerFactory, 'create' ]
        arguments:
            - ~

    erichard_glide.options_resolver:
        public: true
        class: Erichard\GlideBundle\CompositeOptionResolver

    erichard_glide.client_hints_resolver:
        public: false
        class: Erichard\GlideBundle\OptionResolver\ClientHintsResolver
        arguments:
            - "@request_stack"
            - "%erichard_glide.client_hints.dpr%"
        tags:
            - { name: erichard_glide.options_resolver }

    erichard_glide.accept_webp_resolver:
        public: false
        class: Erichard\GlideBundle\OptionResolver\AcceptWebpResolver
        arguments:
            - "@request_stack"
        tags:
            - { name: erichard_glide.options_resolver }
