services:
    Erichard\GlideBundle\Controller\GlideController:
        public: true
        arguments:
            - '@Erichard\GlideBundle\ServerRepository'
        calls: [['setContainer', ['@Psr\Container\ContainerInterface']]]
        tags: ['container.service_subscriber']
        
    Erichard\GlideBundle\GlideUrlBuilder:
        arguments:
            $signkey: "%erichard_glide.sign_key%"

    Erichard\GlideBundle\Twig\GlideExtension:
        arguments:
            - '@Erichard\GlideBundle\GlideUrlBuilder'
        tags:
            - { name: twig.extension }

    Erichard\GlideBundle\SymfonyResponseFactory: ~
    
    League\Glide\Server:
        class: League\Glide\Server
        public: false
        abstract: true
        factory: [ League\Glide\ServerFactory, 'create' ]
        arguments:
            - ~

    Erichard\GlideBundle\ServerRepository: ~